baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[menus]
_merge = "shallow"
[[module.imports]]
path = "github.com/hungryram/re-template-august2021"
[[module.imports]]
path = "github.com/hungryram/yooripark2021"
[[module.imports.mount]]
source = "content/blog"
target = "content/blog"
<<<<<<< HEAD
[[module.imports.mount]]
source = "content/"
target = "content/"
[[menu.main]]
  _merge = 'shallow'
[[menu.main]]
name = "Home"
url = "/"
weight = 1
=======
>>>>>>> 8522a25d60d0a4d9034074511d8a53f539a625b6
