baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'
[module]
[[module.imports]]
path = "github.com/hungryram/re-template-august2021"
[[ module.imports ]]
path = "github.com/hungryram/yooripark2021"
[[ module.imports.mount ]]
source = "content/blog"
target = "content/blog"
[menus]
  _merge = 'shallow'
[[menu.main]]
name = "Home"
url = "/"
weight = 1