baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
[[menu.main]]
name = "Home"
url = "/"
weight = 2
[module]
[[module.imports]]
path = "github.com/hungryram/re-template-august2021"
[[module.imports.mount]]
source = ".forestry/front_matter/templates"
target = ".forestry/front_matter/templates"
[[module.imports.mount]]
source = "data/profile.yml"
target = "data/profile.yml"